"""SQLite-based upload store (#498, #622).

Same structure as ``credentials/store.py`` (#492) — single SQLite file storing
row isolated by ``(owner_id, upload_id)``. Unlike credentials, upload content is
not secret so not encrypted.

Where the bytes live depends on size (#622):

    - Below the spill threshold (``_DEFAULT_SPILL_THRESHOLD_BYTES``, 8 MiB) the
      payload is a BLOB in the row.
    - At or above it the payload is written to ``<db>.blobs/<upload_id>.bin`` beside
      the database, and the row keeps only ``blob_path`` (relative) and
      ``content_sha256``. Exactly one of ``content`` and ``blob_path`` is set.

Staging stays safe in two ways (#498):

    - No user input reaches a filesystem path. ``upload_id`` is generated by the
      server via ``secrets`` and is the only part of a spilled file's name; the
      user's filename is kept for display only. A stored ``blob_path`` is also
      resolved and checked to stay under the blob root before it is read or
      deleted, so a corrupted row cannot point outside it.
    - All queries/deletes scoped by ``owner_id`` — other users' uploads not
      distinguished, treated uniformly as "not found" (fail-closed, same ownership
      pattern as #505).
"""

from __future__ import annotations

import contextlib
import hashlib
import io
import os
import re
import secrets
import sqlite3
import tempfile
import threading
from collections.abc import Sequence
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import BinaryIO, Protocol

from kpubdata_builder.sqlite_settings import BUSY_TIMEOUT_SECONDS

from ..spec.models import SOURCE_FILE_FORMATS
from ..stages._path_safety import ensure_within
from .models import UploadMetadata


class UploadContentCorrupted(RuntimeError):
    """Stored payload unreadable or checksum mismatch (#622).

    Silently returning empty bytes or different bytes would hide what Bronze
    was made from.
    """


MAX_UPLOAD_BYTES_ENV = "KPUBDATA_BUILDER_MAX_UPLOAD_BYTES"
_DEFAULT_MAX_UPLOAD_BYTES = 20 * 1024 * 1024  # 20 MiB

#: From this size, write payload as file instead of BLOB (#622).
#:
#: SQLite default ``SQLITE_MAX_LENGTH`` is ~953 MiB. Real failures exist hitting limit
#: (945.6 MiB passed, 1,444 MiB got ``string or blob too big``), but problem isn't limit size—
#: **upload ceiling accidentally determined by SQLite single-value limit as implementation
#: detail.** Ceiling must be set by policy (``KPUBDATA_BUILDER_MAX_UPLOAD_BYTES``).
#:
#: Set to 8 MiB to stay well away from limit. Small uploads remain as BLOB like before,
#: preserving existing behavior — smaller than default ceiling (20 MiB), so only large
#: ones take new path.
_DEFAULT_SPILL_THRESHOLD_BYTES = 8 * 1024 * 1024  # 8 MiB

# Max preserve length for display-only original filename. Never used as filesystem path,
# so don't need to block dangerous chars, but bounds response size.
_MAX_DISPLAY_FILENAME_LENGTH = 255


def resolve_max_upload_bytes() -> int:
    """Read upload size ceiling from env var (default if absent/invalid)."""
    raw = os.environ.get(MAX_UPLOAD_BYTES_ENV, "").strip()
    if not raw:
        return _DEFAULT_MAX_UPLOAD_BYTES
    try:
        value = int(raw)
    except ValueError:
        return _DEFAULT_MAX_UPLOAD_BYTES
    return value if value > 0 else _DEFAULT_MAX_UPLOAD_BYTES


def generate_upload_id() -> str:
    """Create new upload_id always matching ``spec.models.UPLOAD_ID_PATTERN``.

    ``token_hex(16)`` always returns 32-char lowercase hex string, so always
    matches ``UPLOAD_ID_PATTERN``(``^upl_[a-f0-9]{32}$``) structurally.
    """
    return f"upl_{secrets.token_hex(16)}"


def _sanitize_display_filename(original_filename: str | None) -> str | None:
    """Sanitize original filename to display-safe string.

    Not used as filesystem path, so goal isn't traversal prevention but keeping path
    separators removed so response readers don't accidentally treat as path;
    keep basename only and limit length.
    """
    if original_filename is None:
        return None
    stripped = original_filename.strip()
    if not stripped:
        return None
    basename = re.split(r"[\\/]", stripped)[-1]
    return basename[:_MAX_DISPLAY_FILENAME_LENGTH] or None


@dataclass(frozen=True)
class UploadUsage:
    """What one owner holds: the number of uploads and the bytes they take."""

    files: int
    total_bytes: int


class UploadRepository(Protocol):
    """Upload repository abstraction keyed by owner_id + upload_id."""

    def put(
        self,
        owner_id: str,
        *,
        content: bytes,
        format: str,  # noqa: A002 - match contract field name
        encoding: str,
        original_filename: str | None,
        max_bytes: int | None = None,
    ) -> UploadMetadata: ...

    def get_metadata(self, owner_id: str, upload_id: str) -> UploadMetadata | None: ...

    def get_content(self, owner_id: str, upload_id: str) -> bytes | None: ...

    def open_content(self, owner_id: str, upload_id: str) -> BinaryIO | None:
        """The content as a readable binary stream, for reading without loading it (#622).

        The caller closes it. None when the upload is absent or another owner's.
        """
        ...

    def delete(self, owner_id: str, upload_id: str) -> bool: ...

    def list_for_owner(self, owner_id: str) -> Sequence[UploadMetadata]: ...

    def usage_for_owner(self, owner_id: str) -> UploadUsage:
        """How many uploads the owner holds and their total size (#1045)."""
        ...

    def purge_created_before(self, cutoff: datetime, *, owner_id: str | None = None) -> int:
        """Delete uploads created before ``cutoff`` — one owner's, or everyone's — and
        return how many (#1045)."""
        ...


class SQLiteUploadRepository:
    """SQLite upload repository.

    Small payloads are stored as a BLOB in the row; payloads at or above
    ``spill_threshold_bytes`` are written to a server-named file under
    ``<db>.blobs/`` and referenced from the row with their SHA-256 (#622).
    """

    def __init__(
        self,
        path: Path,
        *,
        max_bytes: int | None = None,
        spill_threshold_bytes: int = _DEFAULT_SPILL_THRESHOLD_BYTES,
    ) -> None:
        self._path = path
        self._max_bytes = max_bytes if max_bytes is not None else resolve_max_upload_bytes()
        self._spill_threshold = spill_threshold_bytes
        # Where file-based payload lives. Keep beside DB file so both states back up/move together.
        self._blob_root = path.parent / f"{path.name}.blobs"
        self._lock = threading.RLock()
        path.parent.mkdir(parents=True, exist_ok=True)
        self._initialize()

    def _connect(self) -> sqlite3.Connection:
        connection = sqlite3.connect(self._path, timeout=BUSY_TIMEOUT_SECONDS)
        connection.execute("PRAGMA foreign_keys = ON")
        return connection

    def _initialize(self) -> None:
        with self._lock, self._connect() as connection:
            connection.execute(
                """
                CREATE TABLE IF NOT EXISTS uploads (
                    upload_id TEXT PRIMARY KEY,
                    owner_id TEXT NOT NULL,
                    format TEXT NOT NULL,
                    encoding TEXT NOT NULL,
                    size_bytes INTEGER NOT NULL,
                    original_filename TEXT,
                    content BLOB,
                    created_at TEXT NOT NULL,
                    -- 큰 payload 는 BLOB 대신 파일로 나간다 (#622). 둘 중 정확히
                    -- 하나만 채워진다.
                    blob_path TEXT,
                    content_sha256 TEXT
                )
                """
            )
            connection.execute(
                "CREATE INDEX IF NOT EXISTS idx_uploads_owner_id ON uploads(owner_id)"
            )
            # Existing DB migration. Column add isn't idempotent, so check existence.
            existing = {
                str(row[1]) for row in connection.execute("PRAGMA table_info(uploads)").fetchall()
            }
            for column in ("blob_path", "content_sha256"):
                if column not in existing:
                    connection.execute(f"ALTER TABLE uploads ADD COLUMN {column} TEXT")

    @staticmethod
    def _validate_owner_id(owner_id: str) -> None:
        if not owner_id:
            raise ValueError("stable owner_id is required")

    def put(
        self,
        owner_id: str,
        *,
        content: bytes,
        format: str,  # noqa: A002 - match contract field name
        encoding: str,
        original_filename: str | None,
        max_bytes: int | None = None,
    ) -> UploadMetadata:
        self._validate_owner_id(owner_id)
        if format not in SOURCE_FILE_FORMATS:
            raise ValueError(f"format must be one of {SOURCE_FILE_FORMATS}, got {format!r}")
        if not content:
            raise ValueError("upload content must not be empty")
        limit = max_bytes if max_bytes is not None else self._max_bytes
        if len(content) > limit:
            raise ValueError(f"upload exceeds max size ({limit} bytes)")

        upload_id = generate_upload_id()
        display_filename = _sanitize_display_filename(original_filename)
        created_at = datetime.now(timezone.utc).isoformat(timespec="seconds")

        blob: bytes | None = content
        blob_path: str | None = None
        digest: str | None = None
        if len(content) >= self._spill_threshold:
            blob = None
            digest = hashlib.sha256(content).hexdigest()
            blob_path = self._write_blob(upload_id, content)

        with self._lock, self._connect() as connection:
            try:
                connection.execute(
                    """
                    INSERT INTO uploads(
                        upload_id, owner_id, format, encoding, size_bytes,
                        original_filename, content, created_at, blob_path, content_sha256
                    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                    """,
                    (
                        upload_id,
                        owner_id,
                        format,
                        encoding,
                        len(content),
                        display_filename,
                        blob,
                        created_at,
                        blob_path,
                        digest,
                    ),
                )
            except BaseException:
                # No way to reach file without row — don't leave orphans.
                if blob_path is not None:
                    self._remove_blob(blob_path)
                raise
        return UploadMetadata(
            upload_id=upload_id,
            format=format,
            encoding=encoding,
            size_bytes=len(content),
            original_filename=display_filename,
            created_at=created_at,
        )

    def get_metadata(self, owner_id: str, upload_id: str) -> UploadMetadata | None:
        self._validate_owner_id(owner_id)
        with self._lock, self._connect() as connection:
            row = connection.execute(
                """
                SELECT format, encoding, size_bytes, original_filename, created_at
                FROM uploads WHERE owner_id = ? AND upload_id = ?
                """,
                (owner_id, upload_id),
            ).fetchone()
        if row is None:
            return None
        return UploadMetadata(
            upload_id=upload_id,
            format=str(row[0]),
            encoding=str(row[1]),
            size_bytes=int(row[2]),
            original_filename=str(row[3]) if row[3] is not None else None,
            created_at=str(row[4]),
        )

    def get_content(self, owner_id: str, upload_id: str) -> bytes | None:
        self._validate_owner_id(owner_id)
        with self._lock, self._connect() as connection:
            row = connection.execute(
                """
                SELECT content, blob_path, content_sha256
                FROM uploads WHERE owner_id = ? AND upload_id = ?
                """,
                (owner_id, upload_id),
            ).fetchone()
        if row is None:
            return None
        if row[1] is None:
            return bytes(row[0])
        content = self._read_blob(str(row[1]))
        expected = str(row[2]) if row[2] is not None else None
        if expected is not None and hashlib.sha256(content).hexdigest() != expected:
            # Disk payload differs from recorded. Silently return and no one knows what
            # Bronze was made from those bytes.
            raise UploadContentCorrupted(
                f"stored content for {upload_id} does not match its recorded checksum"
            )
        return content

    def open_content(self, owner_id: str, upload_id: str) -> BinaryIO | None:
        """The content as a stream (#622). A file-backed payload is not read into memory:
        its checksum is verified in one streaming pass, then the file is opened."""
        self._validate_owner_id(owner_id)
        with self._lock, self._connect() as connection:
            row = connection.execute(
                """
                SELECT blob_path, content_sha256
                FROM uploads WHERE owner_id = ? AND upload_id = ?
                """,
                (owner_id, upload_id),
            ).fetchone()
            if row is not None and row[0] is None:
                # A small payload lives in the row; it is below the spill threshold.
                blob = connection.execute(
                    "SELECT content FROM uploads WHERE owner_id = ? AND upload_id = ?",
                    (owner_id, upload_id),
                ).fetchone()
                return io.BytesIO(bytes(blob[0])) if blob is not None else None
        if row is None:
            return None
        relative = str(row[0])
        expected = str(row[1]) if row[1] is not None else None
        try:
            path = self._blob_file(relative)
            if expected is not None:
                digest = hashlib.sha256()
                with path.open("rb") as handle:
                    for chunk in iter(lambda: handle.read(1024 * 1024), b""):
                        digest.update(chunk)
                if digest.hexdigest() != expected:
                    raise UploadContentCorrupted(
                        f"stored content for {upload_id} does not match its recorded checksum"
                    )
            return path.open("rb")
        except OSError as exc:
            raise UploadContentCorrupted(
                f"stored upload payload is unreadable: {relative}"
            ) from exc

    def delete(self, owner_id: str, upload_id: str) -> bool:
        self._validate_owner_id(owner_id)
        with self._lock, self._connect() as connection:
            row = connection.execute(
                "SELECT blob_path FROM uploads WHERE owner_id = ? AND upload_id = ?",
                (owner_id, upload_id),
            ).fetchone()
            cursor = connection.execute(
                "DELETE FROM uploads WHERE owner_id = ? AND upload_id = ?",
                (owner_id, upload_id),
            )
            deleted = cursor.rowcount > 0
        # Delete row first, then file. Reverse order means if delete fails midway,
        # row remains and only payload vanishes.
        if deleted and row is not None and row[0] is not None:
            self._remove_blob(str(row[0]))
        return deleted

    # --- file-backed payload (#622) ---------------------------------------

    def _blob_file(self, relative: str) -> Path:
        """Convert relative path to absolute path within blob root.

        Path created only from ``upload_id`` and format already validated, but
        don't trust DB values as-is — if storage gets corrupted, path could point
        outside root.
        """
        candidate = (self._blob_root / relative).resolve()
        ensure_within(self._blob_root.resolve(), candidate, label="upload blob")
        return candidate

    def _write_blob(self, upload_id: str, content: bytes) -> str:
        relative = f"{upload_id}.bin"
        destination = self._blob_file(relative)
        destination.parent.mkdir(parents=True, exist_ok=True)
        # Write to temp file and replace — partial file won't be read as complete.
        fd, tmp_name = tempfile.mkstemp(dir=destination.parent, suffix=".tmp")
        try:
            with os.fdopen(fd, "wb") as handle:
                handle.write(content)
            os.replace(tmp_name, destination)
        except BaseException:
            with contextlib.suppress(OSError):
                os.unlink(tmp_name)
            raise
        return relative

    def _read_blob(self, relative: str) -> bytes:
        try:
            return self._blob_file(relative).read_bytes()
        except OSError as exc:
            raise UploadContentCorrupted(
                f"stored upload payload is unreadable: {relative}"
            ) from exc

    def _remove_blob(self, relative: str) -> None:
        with contextlib.suppress(OSError, ValueError):
            self._blob_file(relative).unlink(missing_ok=True)

    def usage_for_owner(self, owner_id: str) -> UploadUsage:
        self._validate_owner_id(owner_id)
        with self._lock, self._connect() as connection:
            row = connection.execute(
                "SELECT COUNT(*), COALESCE(SUM(size_bytes), 0) FROM uploads WHERE owner_id = ?",
                (owner_id,),
            ).fetchone()
        return UploadUsage(files=int(row[0]), total_bytes=int(row[1]))

    def purge_created_before(self, cutoff: datetime, *, owner_id: str | None = None) -> int:
        # ``created_at`` is ISO-8601 UTC at second precision, written by ``put`` — the
        # same form compares as text.
        boundary = cutoff.astimezone(timezone.utc).isoformat(timespec="seconds")
        clause = "created_at < ?" + (" AND owner_id = ?" if owner_id is not None else "")
        arguments: tuple[str, ...] = (boundary,) if owner_id is None else (boundary, owner_id)
        with self._lock, self._connect() as connection:
            rows = connection.execute(
                f"SELECT upload_id, blob_path FROM uploads WHERE {clause}",  # noqa: S608
                arguments,
            ).fetchall()
            connection.execute(f"DELETE FROM uploads WHERE {clause}", arguments)  # noqa: S608
        for row in rows:
            if row[1] is not None:
                self._remove_blob(str(row[1]))
        return len(rows)

    def list_for_owner(self, owner_id: str) -> Sequence[UploadMetadata]:
        self._validate_owner_id(owner_id)
        with self._lock, self._connect() as connection:
            rows = connection.execute(
                """
                SELECT upload_id, format, encoding, size_bytes, original_filename, created_at
                FROM uploads WHERE owner_id = ? ORDER BY created_at DESC
                """,
                (owner_id,),
            ).fetchall()
        return tuple(
            UploadMetadata(
                upload_id=str(row[0]),
                format=str(row[1]),
                encoding=str(row[2]),
                size_bytes=int(row[3]),
                original_filename=str(row[4]) if row[4] is not None else None,
                created_at=str(row[5]),
            )
            for row in rows
        )


__all__ = [
    "MAX_UPLOAD_BYTES_ENV",
    "SQLiteUploadRepository",
    "UploadRepository",
    "UploadUsage",
    "generate_upload_id",
    "resolve_max_upload_bytes",
]
