"""Silver stage artifact models (#46).

refined result of Bronze raw records into Polars table, and schema/statistics/preview/validation.
carries information together. schema, statistics, and preview value objects delegated to
tabular engine (#49). Silver is internal stage model, so table exposes Polars types.

main components:
    - ValidationProblem: individual validation violations (structured objects, #261)
    - ValidationResult: schema validation result
    - SilverDataset: Silver stage artifact
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import TYPE_CHECKING

import polars as pl

from ...tabular import PreviewSlice, SchemaInfo, TableStatistics

if TYPE_CHECKING:
    from .validate import ValidationProblem


@dataclass(frozen=True)
class ValidationResult:
    """Silver schema validation result."""

    ok: bool
    problems: tuple[ValidationProblem, ...] = ()


@dataclass(frozen=True)
class SilverDataset:
    """refined table and metadata generated by Silver stage."""

    table: pl.DataFrame
    schema: SchemaInfo
    statistics: TableStatistics
    preview: PreviewSlice
    validation: ValidationResult
    source_bronze: str
    metadata: dict[str, str] = field(default_factory=dict)
