#!/usr/bin/env python3
"""Write the environment variable tables of `docs/deployment.md` (#1108).

The tables are generated from `src/kpubdata_builder/settings_catalog.py` — the one list
of what Builder reads from the environment — and placed between the two marker comments
in the document. Everything outside the markers is written by hand and left alone.

The unit tests regenerate the block and fail when the committed document differs, so the
document cannot drift from the list; another test holds the list to the code.

Usage:
    python scripts/generate_settings_doc.py          # rewrite the block
    python scripts/generate_settings_doc.py --check  # exit 1 when it is stale
"""

from __future__ import annotations

import argparse
import importlib.util
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
CATALOG = ROOT / "src" / "kpubdata_builder" / "settings_catalog.py"
DOCUMENT = ROOT / "docs" / "deployment.md"

BEGIN = "<!-- settings:begin — generated by scripts/generate_settings_doc.py; do not edit -->"
END = "<!-- settings:end -->"


def _catalog() -> Any:
    """The catalog module, loaded from its file so the script needs no installed package."""
    spec = importlib.util.spec_from_file_location("_settings_catalog", CATALOG)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def render(catalog: Any) -> str:
    """The block between the markers, markers included."""
    lines = [
        BEGIN,
        "",
        "이 절의 표는 `src/kpubdata_builder/settings_catalog.py` 에서 생성한다. 고칠 때는 그",
        "파일을 고치고 `uv run python scripts/generate_settings_doc.py` 를 돌린다.",
        "",
    ]
    for group, heading in catalog.GROUPS.items():
        settings = [setting for setting in catalog.SETTINGS if setting.group == group]
        if not settings:
            continue
        lines += [
            f"### {heading}",
            "",
            "| 변수명 | 설명 | 기본값 | 필수 여부 |",
            "| :--- | :--- | :--- | :--- |",
        ]
        lines += [
            f"| `{setting.name}` | {setting.description} | {setting.default} | {setting.required} |"
            for setting in settings
        ]
        lines.append("")
    lines += [
        "### 운영자가 설정하지 않는 변수",
        "",
        "Builder 가 스스로, 또는 테스트가 설정한다. 운영 배포에서 정하는 값이 아니지만",
        "프로세스 환경에 보이므로 무엇인지 적어 둔다.",
        "",
        "| 변수명 | 누가, 왜 설정하나 |",
        "| :--- | :--- |",
    ]
    lines += [
        f"| `{variable.name}` | {variable.description} |" for variable in catalog.INTERNAL_VARIABLES
    ]
    lines += ["", *_naming(catalog), "", END]
    return "\n".join(lines)


def _naming(catalog: Any) -> list[str]:
    """How settings are named, and what happens to a name that changes."""
    lines = [
        "### 변수 이름과 이름을 바꿀 때의 규칙",
        "",
        "설정의 이름은 다음 중 하나의 모양이다.",
        "",
        "| 이름 | 무엇의 설정인가 | 설정 수 |",
        "| :--- | :--- | :--- |",
    ]
    for family in catalog.NAME_FAMILIES:
        count = sum(1 for setting in catalog.SETTINGS if family.holds(setting.name))
        lines.append(f"| {family.label} | {family.description} | {count} |")
    lines += ["", *catalog.NAMING_POLICY, ""]
    renamed = [
        (earlier, setting) for setting in catalog.SETTINGS for earlier in setting.earlier_names
    ]
    if not renamed:
        lines.append("지금 읽는 이전 이름은 없다 — 이름이 바뀐 설정이 아직 없다.")
        return lines
    lines += [
        "지금 읽는 이전 이름은 다음과 같다.",
        "",
        "| 이전 이름 | 지금 이름 | 새 이름이 나온 릴리스 |",
        "| :--- | :--- | :--- |",
    ]
    lines += [
        f"| `{earlier.name}` | `{setting.name}` | {earlier.renamed_in} |"
        for earlier, setting in renamed
    ]
    return lines


def replace_block(document: str, block: str) -> str:
    """`document` with what is between the markers replaced by `block`.

    Raises:
        ValueError: The document does not have exactly one pair of markers, in order.
    """
    if document.count(BEGIN) != 1 or document.count(END) != 1:
        raise ValueError(f"{DOCUMENT.name} must hold exactly one settings:begin and settings:end")
    start = document.index(BEGIN)
    end = document.index(END)
    if end < start:
        raise ValueError(f"{DOCUMENT.name}: settings:end comes before settings:begin")
    return document[:start] + block + document[end + len(END) :]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail when the document is stale")
    args = parser.parse_args(argv)
    current = DOCUMENT.read_text(encoding="utf-8")
    try:
        text = replace_block(current, render(_catalog()))
    except ValueError as error:
        print(error, file=sys.stderr)
        return 1
    if args.check:
        if current != text:
            print(
                f"{DOCUMENT.relative_to(ROOT)} is stale: run scripts/generate_settings_doc.py",
                file=sys.stderr,
            )
            return 1
        print(f"{DOCUMENT.relative_to(ROOT)} matches the settings catalog")
        return 0
    DOCUMENT.write_text(text, encoding="utf-8")
    print(f"wrote the settings block of {DOCUMENT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
